name: PMTest_gh
on:
  push:
    paths: 
      - 'PMTest/.github/workflows/PMTest_gh.yml'
  workflow_dispatch: #Manual trigger
jobs:
  cli: 
    runs-on: ubuntu-latest
    env:
      #GITHUB_TOKEN is automatically created by GitHub for every Workflow run 
      #and can be used to authenticate with the GitHub API. 
      #It has permissions to access the repository where the workflow is running.
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: env
      - run: gh --version
      - run: gh auth status
      - run: gh repo list
      - run: issue list
      - run: gh workflow list
      - run: gh api /repos/:owner/:repo/actions/workflows